<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dash</name>
   <tag></tag>
   <elementGuidId>3e05b067-808f-4dc9-90d2-97ad55739067</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/main[2]/div[1]/div/div[1]/span/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/main[2]/div[1]/div/div[1]/span/b</value>
   </webElementProperties>
</WebElementEntity>
