<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edit</name>
   <tag></tag>
   <elementGuidId>f9ea4235-4000-4d33-91ca-1c8be6164e71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/main[2]/div[2]/div/div[2]/div/div/div[2]/table/tbody/tr[1]/td[1]/span/a[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/main[2]/div[2]/div/div[2]/div/div/div[2]/table/tbody/tr[1]/td[1]/span/a[2]/i</value>
   </webElementProperties>
</WebElementEntity>
