<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>st</name>
   <tag></tag>
   <elementGuidId>5616bccf-eb91-4879-8b15-1662f861f530</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='myInvoice_form']/div/div[2]/div/div[2]/div[10]/div[2]/div/div/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='myInvoice_form']/div/div[2]/div/div[2]/div[10]/div[2]/div/div/label[2]</value>
   </webElementProperties>
</WebElementEntity>
