<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>date</name>
   <tag></tag>
   <elementGuidId>5b7f6c66-f7dc-466c-b65b-d82324d79cfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/div[6]/form/div/div[2]/div/div[1]/div[7]/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/div[6]/form/div/div[2]/div/div[1]/div[7]/div[2]/input</value>
   </webElementProperties>
</WebElementEntity>
